### PR TITLE
Just updates the wording

### PR DESCRIPTION
**Pull request by blacknight811**
I really liked your article on this subject. I did some small updates to the wording so that it reads a little clearer for native english speakers. I hope this is ok with you. :-)

### CODE REVIEW

**Comment by bertrandg** [comment]
Thanks @blacknight81, like you've seen, this is not my native language! :)

**Comment by blacknight811** [comment]
@bertrandg you're very welcome. Anytime you'd like to feel free to reach out to me and I'll proof read for you and make any necessary corrections for you. You write really good posts and I'd love to contribute by helping edit for you.

**Comment by bertrandg** [comment]
Really cool @blacknight811, I appreciate a lot!

**Comment by bertrandg** [comment]
Hi @blacknight811, I've just pushed a new post about angular2 form (still in draft mode).
If you have few time to take a look this week and point me some mistakes before I publish it, it would be nice! :)

Here it is:
https://github.com/bertrandg/bertrandg.github.io/blob/master/_posts/_2016-07-25-angular2-forms-form-group-validation.md

**Comment by blacknight811** [comment]
Ok will do!!! Should have time later tonight.

**Comment by bertrandg** [comment]
Hi @blacknight811 , I try again! :)

Do you have few minutes to review the latest post I've written:
https://github.com/bertrandg/bertrandg.github.io/blob/master/_posts/_2016-11-25-node-development-with-typescript-and-vscode.md

**Comment by blacknight811** [comment]
Hey! Yes I'll take a look :-)

**Comment by blacknight811** [comment]
My applogies. I was busy the last few days with Thanksgiving holiday and
family in town. Is it too late to look at this ?

**Comment by bertrandg** [comment]
No worries! :)
I published it (http://bertrandg.github.io/node-development-with-typescript-and-vscode/) but i'm sure some errors are still there, so you can take a look.

**Pull request merged**
